swagger: "2.0"
info:
  description: Stranding API
  version: 1.0.0
  title: Strandings Project
  contact:
    name: MarineBio
    url: https://www.marinebio.org
    email: info@marinebio.org
schemes:
- https
security:
- firebase: []
paths:
  /event:
    get:
      summary: Get information on a single stranding event.
      description: Retrieve informatiom from a single stranding event.
      parameters: []
      responses:
        "200":
          description: O
          schema:
            $ref: '#/definitions/Event'
      security: []
securityDefinitions:
  firebase:
    type: oauth2
    authorizationUrl: ""
    flow: implicit
    x-google-issuer: https://securetoken.google.com/stranding-project
    x-google-jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
    x-google-audiences: stranding-project
definitions:
  GeoPoint:
    type: object
    required:
    - lat
    properties:
      lat:
        type: number
      long:
        type: number
  Event:
    type: object
    required:
    - event_date
    - event_location
    properties:
      event_date:
        type: string
        format: date-time
      event_location:
        type: array
        items:
          $ref: '#/definitions/GeoPoint'
    description: An individual stranding event
