swagger: '2.0'
info:
  version: '1.0.0'
  title: Strandings Project
  description: Strandings API
  contact:
    url: https://www.marinebio.org
    name: MarineBio
    email: info@marinebio.org

x-google-allow: configured

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/stranding-project"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "stranding-project"
security:
  - firebase: []
paths:
  /events/:
    get:
      summary: List recent stranding events.
      operationId: getEvents
      security: []
  /event/{id}:
    get:
      summary: Get information on a single stranding event.
      description: Retrieve informatiom from a single stranding event.
      operationId: getEvent
      parameters:
        - in: path
          name: id
          type: string
          format: uuid
          required: true
          description: ID of the event to get.
      security: []
      responses:
        200:
          description: O
          schema:
            $ref: '#/definitions/Event'
        404:
          description: "Event not found."
  /event:
    post:
      summary: Create a new event.
      description: Create a new event.
      operationId: createEvent
      responses:
        200:
          description: OK
    
schemes:
 - https
definitions:
  GeoPoint:
    type: object
    required:
      - lat
      - lon
    properties:
      lat:
        type: number
        format: float
      long:
        type: number
        format: float
  Event:
    description: An individual stranding event
    type: object
    required:
      - event_date
      - event_location
    properties:
      event_id:
        type: string
        format: uuid
      event_date:
        type: string
        format: date-time
      event_location:
        type: array
        items:
          $ref: '#/definitions/GeoPoint'
      event_centroid:
        $ref: '#/definitions/GeoPoint'
      event_regions:
        type: array
        items:
          type: string
      event_animal_type:
        type: array
        items:
          type: string
      event_animal_number:
        type: integer
        format: int32
      event_animal_number_died:
        type: integer
        format: int32
      investigation_type:
        type: string
      investigation_description:
        type: string
      stranding_causes:
        description: "unknown, pending, disease, pollution, vessel strike, bycatch, entanglement, sonar, natural (predator/s), etc., other"
        type: array
        items:
          type: string
      investigation_results_description:
        description: "A long description of the stranding event. This field must form part of the the full text search solution."
        type: string
      investigation_references:
        type: string
      researcher_name:
        type: string
      researcher_email:
        type: string
        format: email
      researcher_first_event_date:
        description: "date of first event approved"
        type: string
        format: date
      researcher_latest_event_date:
        description: "date of latest event approved"
        type: string
        format: date
      researcher_events_total:
        description: "total of researcher's approved events"
        type: integer
        format: int32